State:9
VersionFabric:0.18.2
VersionVanillaName:1.21.10
VersionArgumentIndieV2:True
VersionVanilla:21.0.10
Info:正式版 1.21.10, Fabric 0.18.2
LogoCustom:True
IsStar:False
VersionLiteLoader:False
Logo:PCL\Logo.png
ReleaseTime:2025-10-07 17:17
VersionArgumentIndie:1
